#!/usr/bin/env node
/**
 * ValleyMind AI — sitemap generator (no build step required).
 *
 * Scans the site folder for public *.html pages and writes sitemap.xml.
 * Run it after adding/removing/renaming any page:
 *
 *     node generate-sitemap.mjs
 *
 * To switch domains (e.g. to https://valleymind.ai), change BASE_URL below,
 * then also update the canonical/OG URLs in the HTML pages and robots.txt.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const BASE_URL = 'https://valley-mind-website-o3l8.onrender.com';
const ROOT = dirname(fileURLToPath(import.meta.url));

// Pages that must never appear in the sitemap.
const EXCLUDE = new Set(['offline.html', '404.html']);

// Per-page hints (filename -> [changefreq, priority]); sensible default otherwise.
const HINTS = {
  'index.html':    ['weekly', '1.0'],
  'features.html': ['weekly', '0.9'],
  'pricing.html':  ['weekly', '0.9'],
  'about.html':    ['monthly', '0.8'],
  'faq.html':      ['monthly', '0.7'],
  'contact.html':  ['monthly', '0.7'],
  'privacy.html':  ['yearly', '0.3'],
  'terms.html':    ['yearly', '0.3'],
};

const today = new Date().toISOString().slice(0, 10);

const pages = readdirSync(ROOT)
  .filter((f) => f.endsWith('.html') && !EXCLUDE.has(f))
  .sort((a, b) => (b === 'index.html') - (a === 'index.html') || a.localeCompare(b));

const urls = pages.map((file) => {
  const loc = file === 'index.html' ? `${BASE_URL}/` : `${BASE_URL}/${file}`;
  const [changefreq, priority] = HINTS[file] || ['monthly', '0.6'];
  const lastmod = statSync(join(ROOT, file)).mtime.toISOString().slice(0, 10) || today;
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}).join('\n\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by generate-sitemap.mjs on ${today}. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

${urls}

</urlset>
`;

writeFileSync(join(ROOT, 'sitemap.xml'), xml);
console.log(`sitemap.xml written with ${pages.length} URLs:`);
pages.forEach((p) => console.log('  -', p));
